language: cpp
git:
  quiet: true
  submodules: true
  depth: 3
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      addons:
        apt:
          packages:
            - autoconf
            - libtool
            - flex
            - bison
            - libeigen3-dev
            - libboost-all-dev
            - curl
            - libopencv-dev
            - libpcl-dev
            - libglu1-mesa-dev 
            - freeglut3-dev 


before_install:
  # Install gcc-! and g++-8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update
  - sudo apt-get install gcc-8 g++-8
  # To point to the new install
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

  - eval "${MATRIX_EVAL}" 

  - bash ./scripts/install_librealsense2.sh
  - bash ./scripts/install_dependencies_ci.sh

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage .. 
     - make -j$(nproc)

notifications:
  email: false