##---------------------------------------------------------------------------------------------------------------------
##  MICO 
##---------------------------------------------------------------------------------------------------------------------
##  Copyright 2020 Pablo Ramon Soria (a.k.a. Bardo91) pabramsor@gmail.com
##---------------------------------------------------------------------------------------------------------------------
##  Permission is hereby granted, free of charge, to any person obtaining a copy of this software
##  and associated documentation files (the "Software"), to deal in the Software without restriction,
##  including without limitation the rights to use, copy, modify, merge, publish, distribute,
##  sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
##  furnished to do so, subject to the following conditions:
##
##  The above copyright notice and this permission notice shall be included in all copies or substantial
##  portions of the Software.
##
##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
##  BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
##  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
##  OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
##  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##---------------------------------------------------------------------------------------------------------------------


name: tests_nightly
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: "Install dependencies"
        run: |
          sudo apt install -y git cmake qtmultimedia5-dev libeigen3-dev libboost-all-dev libopencv-dev libpcl-dev freeglut3-dev libgraphviz-dev libgl1-mesa-dev mesa-common-dev libusb-1.0-0-dev libdlib-dev # Common dependencies
          sudo apt install -y python3 python3-numpy                                                # For python and numpy
          sudo apt install -y libgtest-dev libgmock-dev
          sudo apt-get install -y fftw3 fftw3-dev
          sudo apt install -y libgtest-dev   # Enable testing in FLOW
      - name: "Prepare compilation with cmake"
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_AUDIO=OFF
      - name: "Compile repository"
        run: |
          cd build
          make all -j8
      - name: "Run tests"
        run: |
          cd build
          ctest
